import threading
GOOGLE_API_KEY = ""
XAI_API_KEY = ""
MYSQL_HOST = ""
MYSQL_USER = ""
MYSQL_PASSWORD = ""
MYSQL_DATABASE = ""
SMTP_SERVER = ''
SMTP_PORT = 587
EMAIL_SENDER = ''  
EMAIL_PASSWORD = ' '
EMAIL_RECEIVER = ''

CHAT_HISTORY_FILE = ""
CHAT_HISTORY_LOCK = threading.Lock()